branches:
  only:
    - master
language: ruby
rvm:
  - 1.9.3
before_script:
  # Set the git config stuff, so Git stops yelling at us
  - git config --global user.name "Dejian Xu (via Travis-CI)"
  - git config --global user.email "xudejian2008@gmail.com"
  # Disable SSH server fingerprint verification
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  # Unpack ssh key for git
  - echo -n $id_rsa_{00..30} >> ~/.ssh/id_rsa_base64
  - cat ~/.ssh/id_rsa_base64
  - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
script:
  # compile pages
  - mv -f config.xudejian.github.io.yml config.yml
  - bundle exec ruhoh compile
after_script:
  - cd compiled
  - git init
  - git add .
  - git status
  - git remote add origin $REPO
  #- git push -u origin
env:
  global:
    # Repo read-write address
    - REPO="git@github.com:xudejian/xudejian.github.io.git"
    # SSH key. Encoded. See https://gist.github.com/4631240
    - secure: "n4wDxXr9uJgABmy242Rq3wPFwqLY6r/+TUKS6a0P7cvldBUFmmA3H4NJJBVnn3MQtJKB3j+6gat4k9pGceut9w6/uH9Wd9ytiZfDekdILwPjbamVxejzHmCxmHw/PnrUirW1inoKee17IAcvp4msUyllpOw0whrNtXWydHYd+6A="
    - secure: "rBwvCqgnw+BQKGCEXqxS6sxdfv8U4Lak9sJS7W1sMl8iEQalBpo0sn0PCNP2E96OXpRaN7cYPZJt4NR86UmvgynS/jTNKKWrKlst28py374hMtY/841abu4fPtfwfoh8Ry2w/3H2KAKb0YPjZ7Lwgl5GhleLkcPllAQOerxc80w="
    - secure: "T0gnV/H3QxkDhLpb1qbWC3wbwOBvAXM+f/9DrIOkesxhKeeJ8D5/4v/cGnGHL+bhV4RBTURYzQw5fOhleDKxoqArk0/a+cQ43Q/fX5zG1XhDk50yYVSAG9Rn9dFAA4cVyeH1S7hiyqiyQ1osXBm4YhAtdH7fTD1GIJk7S5bbRQY="
    - secure: "qnqAb5wHzrZXHN+PRDmN9nsQ2sLuZxdZF58vBdY/boI03GgaWicdn7CbksMThgpiAEvSYyuqePYMOyxDaA++vRJGnqgh1N9IQ6F5wPMYn6HTum6TBVI+kfO15iiUhh4VTtv/yeSnCyTvLKMuCSLMA/YEQREUg3V7ds+N1ZpGMoY="
    - secure: "aGoN+YjtABRfIj4KiXbEUarL704sZVxZn3Y6g6AsOq2bqb+13eSrC2oLM9BToug7fwyWp6T+SIn/66UjLvpVqlJENOp+Tj93VOeskfb0H0AO2JSFfp/2qk7ordlwPPJ6gepQhn9gDtESVC58yeX/BqEKHorQUSnr73Ye7hb/e/I="
    - secure: "o8MNhsXCWcnF7AZ9zIDWB7z4e3zupmUdNyg6SmwKR0UZa9V7ReTf57mhPHDUYJoaoP3sv1gCIOQhTNR9B55UNRGoZnxT10E2THrjomL++tpAuIsmldSKjEyvMY0o9cpNNeRZwsYv1HuPqKG3XIj+hlQtCysAS0GEZBAUsDcke3g="
    - secure: "KH8FECWcUV/IiZYQJQkk9jojQf8UM92UpbIfaE5mT8+mmG7aiFYzOoWhwY32Yqu9aajgMl0lu1rdTh0LWvY9vENS91kWOicJjVQBSIib8l37Q55dAdlWSES2TegHPFc7sf278RuRWZ9ThnJfGF2LUlyMK/NgR4qiPmXrIejTBGI="
    - secure: "DkVw3XixdkHv75tcjwk1lK4qbTD1lyxpWiCgi6RyiUM3hJ0WWv4/4QRsPE3gKWSA87pNSCdo2lt6tbd24ebo3FePWRhFdRKxJ0uIzxUDyDz+hwygdYEOlyI0uy1d8waBcZLph+vQuY/hy9J7SYKfJdbP77Owb57n7ey1GJXs86M="
    - secure: "VCSlwpxXtilg+PiD2WpO3KL8NIdPzspWDvnlRX8kz9kU62rslpqq3BENjk/PZv9VplqQC7Al5oUWgfyWhRpgdoiCjSSMkbUkbLAeykJQIrNDG9fg17UWefoUn3I10lQG7eHWC74aDlUiU6q0rzL1E8fL2MRmTiECt1x56kzP8JY="
    - secure: "Gvsr7obmYbYAf3F1kMt3Cc+cmTgeo4d5laNKRtehxEv7/NVuBaQjlQHpMry901uVKvu07PuPEbp7sernJwcLRbRMQmDkNi/Wo4U+SxU2RDJs/FnbsZO8c66G4LIo5/juwi6CQ86Otqam9X6fmAEMA/blMI4HQSx9jysp41VD1nI="
    - secure: "qK/ZG0GJRe/acf/JIiatPbFt362P91C7Do2Sw9z/uHs0XZFyMrCPMtkByRf1g6DremIp2Ff5VLBkk+FBsjY/Ysh8UQjIRSX6xaN5GeIjMjDR7xZ642fygAPngBdfjsmvRD5c+HYhvWoobNWzCSbrE/7njB6hG1MFzD962VVoO9o="
    - secure: "DJKyM4XIKdAx8TuMH0pkVGHj3DSSqlsiXBgefgowhfxCgCNjGN7BB/GV9I/nGz4ws20C8O2TrWWBNSE96LW8cR3Xn4RyBUcpjl7doFtpCnR6L3Y0xmG2sDZkEVj+BKVAoFh164bD22E0rKocP/CtICVK1qzwLqLlk8MI0IzH11Y="
    - secure: "JPXtNXdAxfo9+kEX2syoT2RL35TUYmzKc/KYKj2j5FK43ZrYSkXisOyWm7/1Oz5ZqxTrOXsHINeMCpe6I3znPSifPX5dIhPFgy7V7jVE4aLDCkdNMntcoXTHrxfIeBz1DnUerdFT0hy9cLXiAol2NvJZ8vWDQXszK8dDmEfR+hc="
    - secure: "o/61z0jpPF8+J+0VaeU44oSih530+VOp92Bx92/VzeMwceh1S8bwqXPaAGxwcl3IFs66gZiOB6kIXZF7yP3nWK1L3kKOn6XY6gsAbdYWWugSTREpLBCaC/6hRTX97e9/XYBnDFK096cFJI5k2+q1mhRCeJhVbAY9Gc7YcLUiuEU="
    - secure: "UQ+IGoYgNxogBLEx+IYaxzj2YuSVhwE56pNmoRLcKCoc1F/HznZvN0o9JskAizpvCWypNUVeRtkdClBQYQdN7Gf8VyQXO6gdAmpM8y+PYHVU5YM4jgIPmvAUt1nrrLaiRqsF/o9SF+7YnMHdIosmXHhh8xc+iRolwniNN1L5+Qg="
    - secure: "NJvdfTz4PCR3RPFLkbn9RtyXuR3PC+W5viwoLhyEHZeoc3wzXaAA6kriYGAnNMHmZp6DHxeUfbAyK9uxJY6ViJG1iVMRU/9jAgTkHSk3Z9HXbV9Z6LEGPflZAObW/DJFOVsJftt2VxV8EmlCqdKrCvB2lc9Jhc8M8J9TmrU89EY="
    - secure: "hiA2rO0uRsKKET6SEuEyRWzP0PrgpwXqSU105E2BEGQ64tNrV25eHjFWbOOS/tp2lX0xP9Q3AIaAVDfmZrEzjPZgkbJr+y9zk3bGcsLyrWFxNZkT3xzb83NvR4MQ5lEPXM3mpkg+RzwwBkZObPmh8XYrtb0aW0Jw/asSVwwjVFc="
    - secure: "Is1Y64q8/ppfRrx3buyOdWuM2eRiU8rNGCD/tubkUeGN1/k0QVf/EdmW834opyVov7g4boCI5BfybQOzSgIuZLYK94jyby7mca2bq/qwqDM+QKzZFceJrgQA/qDcZxNX10Jawv+eDJXEw819c6hdzskvQgg/OKi5gtMHnv+eaAA="
    - secure: "IZPFzINbf4T3SqcHrzSobEP0ufngwNjJpHqyKyTNO4d45V/qAaPBut7KhRStNILHYzxVN7n5XMNuBNaemRYRyf4bmDzZETTfPP99RIvInlQyx6I/tqCJLFtgV5+8keWvd6Mdzz2Rmd0JC9w3JX/PXYvBfg9W8lhlZ1Er8hECqjU="
    - secure: "dMBZ1LytZHqAFx9UidVX1XfyJ1PFUcO4bVE12V4QxuXcrqCPdk49toxQ4gNaHOSwa/w/JA4ZiqS1srhxDe+c7arHagXOU+RRKnhbGrCAKWKNk9NBp7iEPvLAevNlWR0v/5kbF8XSZDEFgC6vKSXS07oLoU5ZUFpmuQDMlGXzBQk="
    - secure: "Q6oTqSHYvGMHRxlK4MHbJQl3YF4iHcUR7ibBFVxLMngHfKGHIBz7V3rdPHh3L+F/8JQgtul2M40u/O+p9DBLst4GoiOm9xGYJYS1Ri8qvn25Zju2a0iAj2gIOKeUTkG873koJ8CuA/XUFWSdW3gWGyPW3DDofBTpBztGf/3sjO0="
    - secure: "EuOxPcQRfmS3xE3FwGbLjW/jNDpGI90juNjL+b/3kRy56QIUh/gqGfX6ftD/SB8NLLeSMpBQUzC4A2eZ3C7z3VqK+qyFZssWL7udFX3DgGE6Y/AiTucZI2whbE5PMHrU+O4QR2xz3zb0B16r4xydY+ViNloinRTenhvkkzUrNa8="
    - secure: "Vrw6STuZ8Xe1IcWLyyncgsAmJCoq2xFD/BCaH/VVm5fu1D7S+Br+eC88McyIrMTnfaq1EeBxiSyOXbdwzDnS5GDkfTrPUAu7XtxclZr/pwcqTYWeYBHiJcKqZorgwUZahTtgdnFb5m2ehSPWXDL3O2qxgufq0rs7w0lTLS6KAPs="
