branches:
  only:
    - master
language: ruby
rvm:
  - 1.9.3
before_script:
  # Set the git config stuff, so Git stops yelling at us
  - git config --global user.name "Dejian Xu (via Travis-CI)"
  - git config --global user.email "xudejian2008@gmail.com"
  # Disable SSH server fingerprint verification
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  # Unpack ssh key for git
  - echo -n $id_rsa_{00..30} >> ~/.ssh/id_rsa_base64
  - cat ~/.ssh/id_rsa_base64
  - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
script:
  # compile pages
  - mv -f config.xudejian.github.io.yml config.yml
  - bundle exec ruhoh compile
after_script:
  - cd compiled
  - git init
  - git add .
  - git status
  - git remote add origin $REPO
  #- git push -u origin
env:
  global:
    # Repo read-write address
    - REPO="git@github.com:xudejian/xudejian.github.io.git"
    # SSH key. Encoded. See https://gist.github.com/4631240
    - secure: "bFryBBdKJ+FWuYehYv3+bUFWa1pFjBLuAmNPZKlywtWt1cVDqXjbpNeQqRPqBE49xQ3k2ebo0qbCeCvsmm0I81yyBG/Etidqa8ucllAN7PI7wtYwo5Eu4+Nfi76t5FGKNR3Y/EuEjGn0q2KcHpLLC83gM57UtwM9FYDhIwmu6CQ="
    - secure: "YkjhiHUZBvAwX7pp34sd/oLCF1FvHlQG0LJpe4yEDfrwHSmayJXUtOdK28Qxc2uMado2zTkI40rYYmOy+UY/rMy6ukBeVHCiFFzVsiq+OgR3+DAGaeZSOBOz5ALy3csro6S5zewI7ZRttZqIDzAk99A0WokTqCzQpld+S2/FfwQ="
    - secure: "UEA/tFEHRpk2Vm5wtOpKh3uET4ADbUby5APmHsj+V4U3clbWIfJ97saZG3sFerDHYYFkKxMEY4EO7E6ahJ7ZASvJ7b0CZKcB3FQGeLegdpuhaaQllwBNggjSfTMiF8ll3xr4e4f8oYknrmyIU89WD1fofZfKDwjRH7ctqbl+cEc="
    - secure: "YRRq60GzxbCPF8vnByAxEBvZWD0PNeaf4aYZb7Hh3wA4GtN0zO4qmdzbXOyBjeWDIxwyCTcJzOD8FUOOQX6zTcyMSIFYQt9MJh8LDU7qL+UEXvOFyunlOb10Ivhuu8UpkVjxQhx5WHs7ISugHgKjT7pv2uZKEQah1OD+tId/VZo="
    - secure: "YxpWkqO6vjLnNP8ljrwpQFICm/tyn+AEdZFHSiizcXthNN9w/UuO3yhmhtJ/z79ZZpJMrpVeza4KasiMp863u1x5CV+3i8sHQFNBBiMhghmERzfWHig5gbg+BCaQYAVWTFgqDr/WOePUc880qSjpXZF+VIzVYKRhCEbyAoSb+Ck="
    - secure: "BG5g8Is8e35h0gdhmy5DvuMB+6RlUcs2R5j+Z1kLb6iRZ+8cRe2gt3ckUoxMPq5ttDQiQdR+CAphTI4WY3F6F5UE8n+cqFtC16d+3K/3Y/vnnoDn5CdZ1E9XJamVysv/lEF9P8yaY1OyKE9rH73zjqBeQhEvp70esrb0sxQzOfc="
    - secure: "oIGwmpkDxYgqCGM1VP+Kv2Yx/oo0QvubjyqaPRAiqR6S8eTwUekXiRlvpkBiQRJV45+2FZ6fjOIdqLYXVFA+Bco4XBXoZm8ckCXtXw9t46NMpFRibkzVzMSKh73lip/054JeCSJEpmUd8t3JSueR36BSnvwptkcm0eJWJbQbAow="
    - secure: "nfCxAt1A63P4TY+A5k/BzH21HdfzWjR0am+9v7M5Dhs4TmHbzQWl/ANR8bpCOJFZVrTFH2P3k0CxmBXF0EHqexR+FUUX1zWyBvKMHthlCyfmFbqYWD1Dsi44i54v57U/kNUhGfs6GcqHND14YoI4A0mpDGtoJuxjG1M4JD6AJ2g="
    - secure: "dK52rJ7VZarKUmXtwG5aRNvI6kcJxeYQ1145+b9uPczfsbTnUCBr2aHNcQIwqmrRq1QUO5ek3UM58bC1SMAIzMX/eYFLexrERMnzZR6cjOIc4qYpKEUOyfktgfs5ms0/lUvVQxXhBNVQ+LGX5/B269zsNPe7jsb5a941iuG9o2o="
    - secure: "h2SYERahhHXQlpsODb/s9nxb7/quGfd4fzEFpSlXLtX0S11G+l7aLlUlEoCDocT0QCT1fybBr6H4jjC4ouWg2ahZBxrbahN3MuZF/yqeThR5eH6QFnxhycxXWcsNS6fEy4GwcgTrxTbrTFyEc5bHWh8w/GtmCT0AxbWE9ikgRPo="
    - secure: "aHzS9pHczxYBm26cuDLIIKQs59aFpN7u2SWhnGouE7oqTYJfShNbdeDmZKWl2x0Ju/SeqBYgwhjdH4WKhWa3YGDs8Y+w7IdZI2WlaHRp7tCBP7gDcIJnT7EzvOKRoIJ3vkIawrM/lChsrB49KwZ4Dgs/vHcUf0+DEu2zXuUY9oE="
    - secure: "GaLZqyBQCLc3HmjytbDF5wxYT1Q56Z3JgsX4Qpu7eR65s/yGGM/oOgvqNVD9v+5z1sSF3MOq4BzYURFDvK8fBNmVwR+o/mamSHesvmf9KUzshAka8O4fWSM2Dq8Qq05zQ6K7u+9R8BixPjGaCmwkOuEBnde2/c2ET0qVofV5oSA="
    - secure: "e0lwfwwhmGfOw4ZLMFjl3HolTpsg4JRFSH8ulskcL3G+u/hDbEGGqfEWCD8+an/nGAPKEriOx5mJdXZLtPJ9LlCythgVOVKfVToooSZ+HbUeuu8vxM6QNf+GqEwzmdr/Iy52e5QnZzQayiK5lpW0/j4iw09rS3acXFFnzEZ2Zcw="
    - secure: "EviYtE39Erlzw9V9B4GkSYA0bQ6K4WeBU6M9T0dEB0gjH41rE5eJo5B5GcchrZ/3cytf6fGi7TVZLYeP8dbvMtoEW7iXNoHFCfp2DYN/G+2+NqQeKSHj0IWqlJvlIV2H2LVajbNWfW1cu1FGW8VRBdhWg7oQ0gDUDV5swmPhgHI="
    - secure: "hXQakCa+57tYrtYBtzUDGkOXlTL1CtHL8YPs55HGGZ+s9Eb5XB6/1poT8HbO4DZqGSPB5CfBjelMersFvFn8bdfkEkxRNOGgRw+6gmMDPw6h3YsYFioM0VZ8gz4dqEcYVBt9XKCG6DnIDcxY9GFU1fL19hiN4Xpb8W/U+UImV4w="
    - secure: "g7Htdy8VU6WL0ZeUQlDIszZQo2d8G52z+168IIdDfbXAudli5A3rDFN1l74TD8HYtAwSHbFFgJ1yzY7Uz/lT54BPJvUU7Wcmd7oNOPkmHHbVDYLn3Qb3Brt+naAP/tpL52Gp4vneof0OaQZRO7HJdYC6JfYi+B1+lHGwUMnzTLM="
    - secure: "oynrqnvlcxkdLHxuzW+CAjhMMutYW6Bcmqi0pBfP3TTug19VizvNw1OVqwC9hwFQoHanY4ycWGtKrHYIhgPiXIE0bH6SvsXFLKmd+e2asVuDYURLub6uQcudvSMRWrl+zzcdjMSQqwPKe+CCg24Td+WEAGrWZYkQA63wpNPQI9A="
    - secure: "QLZguJBkBroqJJ89lAt/TVrzKmdeMbXanRJy/SUT2VagzRPTHN0eYE1tEMV2EjIgDO9qO2g6j3HKHTuYBrsmjJbKpBxqUWTK+Lf1kBkCnRSY+TOpIzpbiB8U8p4NOsmppfJSSrbXuFqUhpsTpaCtErsv4K6h4VPHjoHSf+Vx04E="
    - secure: "paucB/kGvzvYMopdl/Ejfoek/cpMsxtpZDRjSYOwakZSaY1xw6IXVXeXhHp2/qeUd8HCvjUYL3rLNC2JKnZYd0XGe2npHpfE+UsL2QM261275sjdhYAjYG5jv+vKloOHZTw/3h6SBd85BESueEw38lEItyrq9vScNl9SYe8Mlro="
    - secure: "QAcRMFY5pcGH+yI/j/vVCfmdAWJeYtKqm6854tGb1bA0nV16zOkjrC7BWv2N7cWVag5Kvy1zZj85R32CFS7FTX9DAWy9yRwQ6KUh5R46oMXwqUTk09D05LzaUBZIAz1H26d1e74ec1+q0ZNlkAwogpRHjA65oiX9mdw08sSQ92g="
    - secure: "diQkcktfMlRCNCYRz6hqCL13hPLaD7Ccu2VBRCJp/ZeYC9ZDvjvIY0AFmjJEJnr9p5Qte993PxZXN8zQZnYt67X/AXIi8A3MVYNIqUOLNNTxDztcLsZCZlV95Ud2wmAQEBeVK1DH8TL3V2TgTGaaG4WFzbQ1OxKE5qpW+vR6I9U="
    - secure: "i5ZpENMcX0S3gwcl7khR4Fy65M/bMZlpELRzlQt7L+lzt7oLvmOAIO94i4QWRPZ4msEEoK/yJgkEQu+y/rNVN0NWDoH7UZjF7XNFsopwuOq0JPsptA7oeZJoT4zZ0xyeYUUaMh4dwRfRq97kextExNxnBR/tMWh0x2cP2KK0SXU="
    - secure: "qCcE5gdGLuDyDuIKMNdbTD3mWxT7GiohLUM1xsz2+6olTIw5urWuO4Q5zgR4O3ZV2H0L7n2WLvjiCoCdRDpWHliZrBGoj0wbXpynu3wc8aVIlYCGjhigKLGttMSgQlLdYFHnQY3+5v0pz8ARxSUhm/4nDhSRf0UARaF4CLuwyUE="
