branches:
  only:
    - master
language: ruby
rvm:
  - 2.0.0
before_script:
  # Set the git config stuff, so Git stops yelling at us
  - git config --global user.name "Dejian Xu (via Travis-CI)"
  - git config --global user.email "xudejian2008@gmail.com"
  # Disable SSH server fingerprint verification
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  # Unpack ssh key for git
  - echo -n $id_rsa_{00..30} >> ~/.ssh/id_rsa_base64
  - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
script:
  # compile pages
  - mv -f config.xudejian.github.io.yml config.yml
  - bundle exec ruhoh compile
after_success:
  - cp baidu_verify_25JCE7NwQ9.html google3674f8fdb9c1b1b4.html compiled/
  - cd compiled
  - git init
  - git remote add origin $REPO
  - git add .
  - git commit -m 'Dejian blog, automated generate from CI'
  - git push --force origin master
env:
  global:
    # Repo read-write address
    - REPO="git@github.com:xudejian/xudejian.github.io.git"
    # SSH key. Encoded. See https://gist.github.com/4631240
    - secure: "Bv/vboPkSTntQhEC3VRGipbGZ0IEyfrcqwj14+7hFSn20/RjHFf1gSl7C/Kybs59d1+sdMIdj0JUvhkYJoO+YhUEyXVdHsY184cAMd3/MVEGbOck4l3aqOvP7ZeHsgNNvN3XbnM/kMxtMGLUXsSbAY2BEOzGLZIAVMO4mSBIi/k="
    - secure: "FTvssoNpfQ+zaFQxu5epInrcsqnkOc1qZaXsx0fpWrMXgghlPRbtl6q8isANCjwffblGljl+5y+E8p4mxb52kk8u9YiMqMroBlERxr3/a0+8cRFkH6K/OK19ddJujDRFA/ZsRgOisGEUitcj3FWofPGAY535FavytxVKKQisJeI="
    - secure: "A0sQdlDKIwXoRiHKGKPBFb2kz4S1PNeTGIT9ekxLoylM5OVO9U6PQ9AJTo0vwHDLDLi38YmGSrKRgxTh9RM0s1/WUzstQGoGhRQt0HkhukPit561iSR9bi1EhjOM6UIOrtfnOqA/+vXeQDm60pq45+fgfUZYYZzvmhX9hNJXvUE="
    - secure: "L/MGiLHXzXO5ApBLBrrN0yZCTZNmOneK7q2s3Y3WRa8glT++2t7g55I9b9gpAyPjLrkNrIJBfsNJluKj0mbGtrdo/se4eGsHW8zqtUxymQUviHzUYPo4Vn5hWVl0gM8CrSOcTyNbJBeJJ6OXU8bZnwXEtzM84qSj3yEhxdK7Vec="
    - secure: "elra17iJb/dFTjFOXC2ItBykfggsfrPGpiPPNLFQrpjqEH7dzFxhWUXHBco66b9VB+jrPug6uwFVneh7oNR5VqtAzskvv3F2/sxrzHAzNI9UjZtIdoiayp2e+fNglxd2DjgyvjsSJUrbr4fnVJZ7705NdmrcMEW/BjAbKnj0Tfs="
    - secure: "g74ckCyzgOJNKCv2jMONL2sRklI7U5hM9xS53ewBwiU/5snbzv86fxZUw7PGn56Y/JfWPYX+vBMmhT8Wi8HLrGc2P7cAxqLqHX++BC+kvcDwCDmVBxndJCB9O8xV5eqUbgfLngFNNLAuxoilodISXFEBVpZC6JeGBrY2w2VxN4U="
    - secure: "A0Me3ZeauFRXSxeIyNoOOmoCq0hPq3kNHzQbK4Ki0ZJQqoYz9Yh4P2+7vCHHHP6h2p/ou5D39WacRbFka665355KEdtyEaq+nimL+3HyIRc1q5+gJdAPxvpl3CE6Ywu/eBnZ9qtlslbt+vGwT8Tn6OLZByVkJDfq6F2G+5EoT+0="
    - secure: "JIhpZidXnMEo9c7Mw6qmgHGWC6WG6bjmDGukjxhC4fUSWfCdXsSSfwLk4dy/X9ggf6Pa2wdhWahIfgixo3cIw8skMoo/jPkIM9mL76Z9DEzSYw9aB/XpcCha6REmzcwFKE6R08XI0XHAbo4JJ06t2cRXnkmo7jEnxxHLKPFVq38="
    - secure: "g1zKAFqRGL4rYOLwO1AALjB96Wtc+kloPbbUxhl6KzHUlZFy5ZDD6imgMGDJCSWiBCpICoy4v5cAyl1Cw5KCb2IjKGQHx3f5yKe0lvo/vkbvLPjpBNO+bTUc5N7zMbPbf19wJzV29EeV+hn5oFpByMWTJtm6281QBD51Yhdc62c="
    - secure: "FwL8WuRcw8SC1F9yBByGLPLUlauWi2iDsLcFvOccdwnMMYtub9T2+Rfnj8nPCHkLeQKtKZfgyCpRob3XkS5lNm0g0do+xzlV4cUMNTsEBUQVSAPdZyy1Ze1zpMcVxZNbyJrj9IX/LbUM1VeiMTMrq/9l7xZTkoNmlpKttEYSwWs="
    - secure: "KwJX3PqNABsaTf4thbyR6Ra9DbS9OrMr+mt704Y0Ld+2PBjLiHmlehnB4aJGrpSiM074MWHGqJd6tDvauUwziKIM3FS17cRBw/78Vg1OPBcDOCb12EBkZEGzfb/906ye8wU3XQc7pZCX4wuarxY0Qbhbaw5bDGbqNEWLmO/tjF4="
    - secure: "G01PmmFagFljnSF/fTY6Inp0vxdIrExsjJ9Xtmb9rO75Z/sXJQ4aLIDXV1s+eozl5DLsXTvvnbQrrGgaRQ8BKP7VjARNsIw8m+XByua0LtIPoBokmnNvX0hauOwC/3FJkQC8HIageMN7oRmbfV166Ifukh/YK0khYceFQGetLvI="
    - secure: "JVnOoFNPvtx7cpXR1ZoTKOFjJ/VeAtb5GX4P2bON8+FlE6RgyUCV06qzfm31dVXsys66zVL/uEdqFWvu4bq+3k3ps2vaDiObgx5A1V4PaTpWhvJP9wqAIaWf1Hyso73e1WBjD4hESyKYIIN8Lxbkd5Kf4EpsWwiWccltIFQwLMQ="
    - secure: "QTy9McuVxkL7Kq5nVuIa9m3qPuqMWe2vmAobU0thkDwi0hZQA1nQQDEfGlxhbrAA63Xm5cHoWhCfW6ciPe5VfkZyqu8SwZM3wBN6zk1+L1ePuj6FnpwKDAw6Ep/IGSG8nV9VWEvvrue+0zVFNU39eAwh60rfAh/eOhiJin7Ye6Q="
    - secure: "erfRgRoMeT/OYaOVqyLxeqHx5cZNmZgRKspToYJIiFF0NQS2IoXRNA88QsfPbFaKMkFJVb2uiB6HRId5CFfcmLHJ/BheIvpqEaXqaTssUhi//Ba67MRpYv29iBK0RQVA1T+vt7eB6ZAxe9nJoo1pAdHWNu6GgvGf9QmtGwtdCvg="
    - secure: "FiEOla4eaiT97VPmWX7nw7tBd2zYQDpjsjV51Mgi44jGPdL9P6HVk9jzWiQfpaJohhqJX6GxiUoMvrg1Ik6ypumsVIq8WrVf8zDi9cLSxOBtH8jsT4gY4eyt1nCE8Ze46TMVsc0zO4VPXlGgd76LXKVteA6nByCWEyowvRnACmo="
    - secure: "iAuy4wad/JIwIAlFkWhBiKI0giliux3MPlM2eO/7hSmYA26wjgcJXlhcRPVnT9RJ7+BF8xXsaaL4s+dXo/56daCGEV2wjoxKEGpGdXVtaYzKq2WJIYcThHa+ltkhZal6iftXUbygiu5yJ7d4eM2rVZfGgq3MR2pGrsAcqBgsPzQ="
    - secure: "Xh33DX7FmwVWYPQSgcO+aHxLTcPSWaVDfH3kPg5iVYhYQyrRVAjmmpBYSj3rRkOiBI+tHO8KFASUSakPcZ7NvT/L/41Rh3DW5uZo0U45emzMNUzWEARxnvnVHOk7Qo7bAlgkU+FmCCUKjFLdeLC41r3dvwZnZjkthWiwj5V9vOQ="
    - secure: "HIVYyC0xtn9amGFx8lzRtuv5u6fPFHL4VWGVSY0geWA9+DwXzcz3zpHjLSqBjH0YpATk7CIiaIlg4PCNlRfok9LOdMpBxBQx5v9JxNq0isbReRXtUlNdOVzapPLG4illM8RJNpiRkiSSncfFZQ9LggfKJgaKLjmgVwQEy+5oi6o="
    - secure: "KLbWTO0Hou6ON5Vf+ZZTGNzF+V1rK7N1JSIaW4tc145zWpmRABSUAzme4FKI9ybvwDENvefYdvh8/uQzQfA42SA/qsdC7euAu5kXgrT5HYT8WChLgAgSD32v2gdWtNHczCdK++H/K35tmJUPSV4CPR+nphuK0DzYVv+Qd+Y3/6k="
    - secure: "ebeV/k9jT50uwTXa1g4TRcyEn2oS2kyuqV5SL8ZlbWs6CDBIo/l1xvjHi3b//9wZ8ei3HkwdJ7XgWUM3b8NyekzGphz5i5dw8Z3MTkp40NYPX0/KR5+VAbb1aGawAAdHp6U6Vdvq0b9RQgmXZv0RECSmfsoH3eSuGP3W4jzasP8="
    - secure: "Q0ODnHDmiwDun6mlxc+Rqg5tIcau19xTYFc2UWnqia2Csd7uDd27n6R0dALLK3mVcVRM3JhGGbgYPiRZGDJacMZXZtiguYPLsG6VKgGBwdMtOGQ6e+mpwhScA52ePNncUBDzXV339U9wAlmpQzptrSlj0cKLQQEb25F5EGKKkw8="
    - secure: "VdCZA5SnC0k0QCvzoQJpufRHLFnQzG0HMwDv5DPNPgdyHSUPzieEgQwq87CnOVY57zgmKSmThpcyEY9VgZLu6HbZjuLOc1EjqMs4q38JoUGdG4Sj18wvjI7udTXWP3VVtsAKLr+NDSKRp4WhII9Vtvg/4QuKPJVARowra6RiK5c="
